services:
  nebula:
    image: nebulaoss/nebula:latest
    container_name: nebula
    network_mode: host
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    volumes:
      - ./config:/config
    restart: unless-stopped
