pki:
  ca: /config/ca.crt
  cert: /config/lighthouse.crt
  key: /config/lighthouse.key

static_host_map: {}

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: 4242

# STOP ADVERTISING VIRTUAL IPS
local_allow_list:
  interfaces:
    tailscale*: false
    docker*: false
  networks:
    - 0.0.0.0/0

# STOP TRYING TO CONNECT VIA IPV6
remote_allow_list:
  "0.0.0.0/0": true
  "::/0": false

punchy:
  punch: true
  respond: true

firewall:
  outbound: [{port: any, proto: any, host: any}]
  inbound: [{port: any, proto: any, host: any}]
